---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2020/4/23 20:03
---

---@class IslandConfig
local IslandConfig = T(Config, "IslandConfig")

local settings = {}

function IslandConfig:init()
    local config = Lib.read_csv_file(Root.Instance():getGamePath() .. "config/IslandConfig.csv", 3) or {}
    for _, vConfig in pairs(config) do
        local data = {}
        data.islandId = tonumber(vConfig.n_islandId) or 0
        data.islandType = tonumber(vConfig.n_islandType) or 0
        data.islandName = vConfig.s_islandName or ""
        data.nextIsland = tonumber(vConfig.n_unlockNextIsland) or 0
        data.islandLv = tonumber(vConfig.n_islandLv) or 0
        data.subtitle = vConfig.s_UnlockSubtitle or ""
        table.insert(settings, data)
    end
end

function IslandConfig:getIslandConfig(islandId)
    for _, v in pairs(settings) do
        if v.islandId == islandId then
            return v
        end
    end
    return nil
end

return IslandConfig
