---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/4/20 16:16
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2020/4/2 11:38
---
---初始化阵营商店物品配置
---@class TeamRewardConfig
local TeamRewardConfig = T(Config, "TeamRewardConfig")

local Setting = {}
function TeamRewardConfig:initConfig()
    local temp = Lib.read_csv_file(Root.Instance():getGamePath() .. "config/teamReward.csv") or {}
    for _, config in pairs(temp) do
        local data = {
            kills = tonumber(config.n_kills),
            rewardIds = Lib.split(config.s_rewardIds, "#")
        }
        Setting[data.kills] = data
    end
end

function TeamRewardConfig:getRewardByKills(kills)
    if Setting[kills] then
        return Setting[kills].rewardIds
    end
end

return TeamRewardConfig