---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/4/20 16:16
---

---@class TeamRewardConfig
local TeamRewardConfig = T(Config, "TeamRewardConfig")

local Setting = {}
function TeamRewardConfig:initConfig()
    local temp = Lib.read_csv_file(Root.Instance():getGamePath() .. "config/teamReward.csv") or {}
    for _, config in pairs(temp) do
        local data = {
            id = tonumber(config.n_id),
            maxKills = tonumber(config.n_maxKills),
            reward = {
                rewardType = config.s_reward_type or "",
                rewardNum = tonumber(config.n_reward_num) or 0
            }
        }
        table.insert(Setting, data)
    end
    table.sort(Setting, function(a, b)
        return a.id < b.id
    end)
end

function TeamRewardConfig:getRewardByKills(kills)
    for i, cfg in ipairs(Setting) do
        if i == #Setting or cfg.maxKills >= kills then
            return cfg.reward
        end
    end
end

local function init()
    TeamRewardConfig:initConfig()
end

init()

return TeamRewardConfig