---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2020/4/2 11:38
---
---初始化阵营商店物品配置
---@class teamShopConfig
local teamShopConfig = T(Config, "teamShopConfig")

local Items = {}
function teamShopConfig:initConfig()
    local temp = Lib.read_csv_file(Root.Instance():getGamePath() .. "config/teamShopItems.csv", 3) or {}
    for _, config in pairs(temp) do
        local data = {
            id = tonumber(config.n_index),
            goodsId = tonumber(config.n_goodsId),
            tabId = tonumber(config.n_tabId),
            type = tonumber(config.n_type),
            camp = config.n_camp,
            name = tostring(config.s_name),
            desc = tostring(config.s_desc),
            icon = tostring(config.s_icon),
            moneyType = tonumber(config.n_moneyType),
            price = tonumber(config.n_price) or 0,
            status = 1
        }
        table.insert(Items, data)
    end
    --print("--!!!!teamShopConfig--initConfig " .. Lib.v2s(Items))
end

function teamShopConfig:getItemByItemId(itemId)
    for i, item in pairs(Items) do
        if item.goodsId == itemId then
            return item
        end
    end
end

function teamShopConfig:getItems()
    return Items
end

return teamShopConfig