---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/4/21 21:14
---

---@class WorldBossRewardConfig
local WorldBossRewardConfig = T(Config, "WorldBossRewardConfig")

local Setting = {}
function WorldBossRewardConfig:initConfig()
    local temp = Lib.read_csv_file(Root.Instance():getGamePath() .. "config/worldBossReward.csv") or {}
    for _, config in pairs(temp) do
        local data = {
            id = tonumber(config.n_id),
            maxHits = tonumber(config.n_maxHits),
            reward = {
                {
                    rewardType = config.s_reward1_type or "",
                    rewardNum = tonumber(config.n_reward1_num) or 0
                },
                {
                    rewardType = config.s_reward2_type or "",
                    rewardNum = tonumber(config.n_reward2_num) or 0
                }
            }
        }
        table.insert(Setting, data)
    end
    table.sort(Setting, function(a, b)
        return a.id < b.id
    end)
end

function WorldBossRewardConfig:getRewardByHits(hits)
    for i, cfg in ipairs(Setting) do
        if i == #Setting or cfg.maxHits >= hits then
            return cfg.reward
        end
    end
end

local function init()
    WorldBossRewardConfig:initConfig()
end

init()

return WorldBossRewardConfig