---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qjc.
--- DateTime: 2020/4/13 18:13
---

local SkillBase = Skill.GetType("Base")
local RoundUpSkill = Skill.GetType("RoundUp")
RoundUpSkill.timer = nil
local control = Blockman.Instance():control()

local function roundUp(self, packet, from)
    if not from then
        return
    end

    local player = Player.CurPlayer
    if not player then return end

    local RoundUpAttackData = player:data("main").RoundUpAttackData
    local entityIndex = RoundUpAttackData.entityIndex
    local nearbyEntities = RoundUpAttackData.nearbyEntities

    if entityIndex > 0 then
        local pTarget = nearbyEntities[entityIndex]
        if pTarget then
            local d = Lib.tov3(pTarget:getPosition()) - Lib.tov3(from:getPosition())
            local yaw = math.atan(d.z, d.x)
            player:setBodyYaw(math.deg(yaw) - 90)
            pTarget:setRotationYaw(math.deg(yaw) - 90)
            pTarget.forceTargetPos = from:getPosition()
            pTarget.forceTime = 5

            local RoundUpAttackData = {
                nearbyEntities = nearbyEntities,
                entityIndex = entityIndex - 1,
            }

            pTarget:data("main").beAttackByRoundupSkill = nil
            player:data("main").RoundUpAttackData = RoundUpAttackData
        end
    else
        player:data("main").RoundUpAttackData = nil
        RoundUpSkill.timer = nil
        control.enable = true
        return false
    end

    return true
end

function RoundUpSkill:cast(packet, from)
    if not from then
        return
    end

    local player = Player.CurPlayer
    if not player then
        return
    end

    local nearbyEntities = from:getNearbyEntities(self.RoundUpRange)
    local ret = {}
    for _, entity in pairs(nearbyEntities) do
        if entity.objID ~= from.objID  and entity.isPlayer then
            --todo delete teammate
            ret[#ret + 1] = entity

            entity:data("main").beAttackByRoundupSkill = true
            if entity.objID == player.objID then
                control.enable = false
            end
        end
    end

    local RoundUpAttackData = {
        nearbyEntities = ret,
        entityIndex = #ret,
    }

    player:data("main").RoundUpAttackData = RoundUpAttackData
    RoundUpSkill.timer = player:timer(1, roundUp, self, packet, from)
end

