initPos: [-723, 34, -229]
manorReleaseTime: 120
inviteShowTime: 20


#引导中没有写进引导配置里面的配置
#引导过程中，让玩家放置切片操作的前一个id事件
inGuidePlaceTemplatePreId: 146
#引导过程中，中断事件不为0的最后一个事件
inGuideLastId: 146
#引导过程中，玩家放置切片操作的后一个事件id
inGuidePlaceTemplateId: 193

#加载废墟
GuideDemoDrawId: 914
#加载废墟的前一个id事件
GuidePlaceDemoDrawEventId: 110

GuideDemoDrawRPos180: [9, 0, 8]
GuideDemoDrawRPos90: [20, 0, 8]
GuideDemoDrawRPos270: [9, 0, 19]


#中断引导之后，传进领地的相对坐标
GuideSuspendTeleportRPos: [14, 1, 21]

#玩家第一次进游戏时显示的默认名字
defaultName: "RealmCity"

#玩家领地释放后用于修复地皮用的模板文件
groundName: "ground_29x29.schematic"

#最大存档数量
maxArchiveNum: 5

#免费给玩家的存档数量
freeArchiveNum: 2

#存档的默认名字 (后面会自动添加数字递增)
archiveName: MyRealm

#每天赠送的玫瑰花id
roseId: 2801
#每天赠送玫瑰花的数量
roseNum: 3

#超市大门位置
shopPosWithYaw: [-723, 34, -229, 90]