initPos: [-723, 34, -229]
manorReleaseTime: 120
inviteShowTime: 20


#引导中没有写进引导配置里面的配置
#引导过程中，让玩家放置切片操作的前一个id事件
inGuidePlaceTemplatePreId: 146
#引导过程中，中断事件不为0的最后一个事件
inGuideLastId: 146
#引导过程中，玩家放置切片操作的后一个事件id
inGuidePlaceTemplateId: 193

#加载废墟
GuideDemoDrawId: 914
#加载废墟的前一个id事件
GuidePlaceDemoDrawEventId: 110

GuideDemoDrawRPos180: [9, 0, 8]
GuideDemoDrawRPos90: [20, 0, 8]
GuideDemoDrawRPos270: [9, 0, 19]


#中断引导之后，传进领地的相对坐标
GuideSuspendTeleportRPos: [14, 1, 21]

#玩家第一次进游戏时显示的默认名字
defaultName: "RealmCity"

#玩家领地释放后用于修复地皮用的模板文件
groundName: "ground_29x29.schematic"

#最大存档数量
maxArchiveNum: 5

#免费给玩家的存档数量
freeArchiveNum: 2

#存档的默认名字 (后面会自动添加数字递增)
archiveName: MyRealm

#每天赠送的玫瑰花id
roseId: 2801
#每天赠送玫瑰花的数量
roseNum: 3

#超市大门位置
shopPosWithYaw: [-723, 34, -229, 90]

#广告刷新时间点(目前两个广告公用一个时间点)
ADRefreshTime: ["00:00", "12:00"]

#飞行广告奖励飞行时间(单位：秒)
flyingAdReward: 300

#玩家第一次进入游戏免费赠送的绿钞
freeR_Currency: 3000

#赛车时，玩家A与B的起跑位置和比赛车辆
RaceInitInfo:
    raceVehicleType: 2
    StartLine:
        posAndYaw: [-453, 36, -296, 270]
        posAndYaw: [-453, 36, -286, 270]
    EndLine:
    #pos=[x1, y1, z1, x2, y2, z2]
        pos: [-264, 33, -205, -234, 40, -190]

