initPos: [-709, 34, -260]
manorReleaseTime: 300
inviteShowTime: 20


#引导中没有写进引导配置里面的配置
#引导过程中，让玩家放置切片操作的前一个id事件
inGuidePlaceTemplatePreId: 147
#引导过程中，让玩家放置切片操作的前一个id事件
inGuideLastId: 147
#引导过程中，玩家放置切片操作的后一个事件id
inGuidePlaceTemplateId: 193


GuideDemoDrawId: 914
GuidePlaceDemoDrawEventId: 111
GuideDemoDrawRPos180: [9, 0, 8]
GuideDemoDrawRPos90: [20, 0, 8]
GuideDemoDrawRPos270: [9, 0, 19]

GuideSuspendTeleportRPos: [14, 1, 21]
