---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2020/4/23 15:07
---
local class = require "common.class"

local JumpState = require "script_client.player.state.jump_state"
local JumpFreeFallState = class("JumpFreeFallState", JumpState)

function JumpFreeFallState:enter()
    --TODO
end

function JumpFreeFallState:update()
    --TODO
end

function JumpFreeFallState:leave()
    --TODO
end

return JumpFreeFallState