---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2020/4/23 14:57
---
local class = require "common.class"

local JumpState = require "script_client.player.state.jump_state"
local JumpRaiseState = class("JumpRaiseState", JumpState)

function JumpRaiseState:enter()
    --TODO
end

function JumpRaiseState:update()
    --TODO
end

function JumpRaiseState:leave()
    --TODO
end

return JumpRaiseState