---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2020/4/23 15:06
---
local class = require "common.class"

local JumpState = require "script_client.player.state.jump_state"
local JumpFloatState = class("JumpFloatState", JumpState)

function JumpFloatState:enter()
    --TODO
end

function JumpFloatState:update()
    --TODO
end

function JumpFloatState:leave()
    --TODO
end

return JumpFloatState