---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2020/4/23 15:06
---
local class = require "common.class"

local JumpState = require "script_client.player.state.jump_state"
local JumpFallState = class("JumpFallState", JumpState)

function JumpFallState:enter(owner)
    print("eventJumpFloatEnd")

    local jumpCount = owner:getJumpCount()
    local maxJumpCount = owner:getMaxJumpCount()

    ---@type JumpConfig
    local JumpConfig = T(Config, "JumpConfig")
    if jumpCount >= 0 then
        local config = JumpConfig:getJumpConfig(maxJumpCount - jumpCount)
        if config then
            owner:setEntityProp("gravity", tostring(config.fallGravity))
        end
    end
end

function JumpFallState:update(owner)
    --TODO
end

function JumpFallState:leave(owner)
    --TODO
end

return JumpFallState