---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bell.
--- DateTime: 2020/3/25 22:16
---
local id = 0

---@param segment number
---@return number
local function accumulator(segment)
    id = segment or id + 1
    return id
end

function Event.register(name)
    Event[name] = accumulator()
end