---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2020/3/26 19:42
---
local Handlers = T(Trigger, "Handlers")

function Handlers.GAME_REWAIT(context)
    --TODO
end

function Handlers.SKILL_CAST(context)
    print("Handlers.SKILL_CAST " .. Lib.v2s(context, 1))
end