---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bell.
--- DateTime: 2020/3/25 22:21
---
local Events = {
    "EVENT_EXP_CHANGE",
    "EVENT_HP_CHANGE",
    "EVENT_CHECK_TRIGGERS"
}

for _, name in pairs(Events) do
    Event.register(name)
end
if World.isClient then
    Event.register("EVENT_NEW_GUIDE")
else
    --TODO
end