---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bell.
--- DateTime: 2020/3/25 22:21
---
Event.register("EVENT_CHECK_TRIGGERS")

if World.isClient then
    Event.register("EVENT_NEW_GUIDE")
else
    --TODO
end