---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2020/3/23 10:30
---

Define.Team = {
    Neutrality = 1,
    Black = 2,
    White = 3
}

Define.petType = {
    pet = 1,        --宠物
    plusPet = 2     --式神
}

Define.ProcessState = {
    Init = 0,
    Waiting = 1,
    Prepare = 2,
    GameStart = 3,
    GameOver = 4,
    WaitClose = 5
}

Define.ProcessType = {
    Base = "ProcessBase",
    Team = "ProcessTeam"
}