---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KH5C.
--- DateTime: 2020/4/14 17:09
---

local petType = T(Define, "petType");

Player.equipPetList = {}; --该表是存储创建的pet的entityIndex，在装备的情况下，可以通过宠物自身的index和创建的entityIndex进行互换

function Player.getPlusPetPluginFromID(id)
    return "myplugin/PlusPet1";
end

function Player.getPetPluginFromID(id)
    return "myplugin/Pet1";
end

function Player.turnID2Plugin(type, id)
    if type == petType.pet then
        return getPetPluginFromID(id);
    elseif type == petType.pulsPet then
        return getPlusPetPluginFromID(id);
    end
    print("=======Wrong pet type :" .. type .. "\nand id :" .. id .. "=======");
end


function Player:getPetAttr(index)
    local targetPetInfo = self:getValue("allPetAttr")[index];
    local targetEntityCfg = Entity.GetCfg(Player.turnID2Plugin(targetPetInfo.petType, targetPetInfo.ID));
    return {
        type = targetPetInfo.petType,                           --宠物类型
        name = targetEntityCfg.multiLang,                       --多语言配置名
        level = targetPetInfo.level,                            --当前等级
        sortWeight = targetEntityCfg.orderWeight,               --同等状态下排序优先级
        actorName = targetEntityCfg.actorName,                  --宠物模型名
        rank = targetEntityCfg.rank,                            --稀有度
        --==================以下为宠物或式神特有的，没有的即为nil=======================================
        coinAddition = targetPetInfo.coinTransRatio,            --当前金币转换率
        chiAddition = targetPetInfo.chiTransRatio,              --当前气转换率
        exerciseAddition = targetEntityCfg.exerciseRatio,       --宠物锻炼倍数
        chiIntensifyRange = targetEntityCfg.chiIntensifyRange,  --气转换区间
        coinIntensifyRange = targetEntityCfg.coinIntensifyRange,--金币转换区间
        atkAddition = targetPetInfo.atkBuffNum,                 --当前攻击增益数值
        reductionInjury = targetEntityCfg.reductionInjury,      --减伤数值
        intensifyATK = targetEntityCfg.intensifyATK,            --强化攻击倍率
        intensifyValue = targetEntityCfg.targetEntityCfg,       --强化权重
        skillType = targetEntityCfg.skillType,                  --技能类型
        skillName = targetEntityCfg.skillName,                  --技能名称
        skillInfo = targetEntityCfg.skillInfo                   --技能多语言描述名
    }
end