---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/4/20 10:15
---

--local entity = EntityServer.Create({cfgName = name, pos = self:getPosition(), map = self.map})

local class = require"common.class"
local ProcessWorldBoss = class("ProcessWorldBoss", require"script_server.process.process_base")
local playerKillList = {}
local worldCfg = World.cfg
local boss = {}

function ProcessWorldBoss:ctor(config)
    if config then
        for k, v in pairs(config) do
            self[k] = v
        end
    end
    local setting = worldCfg.worldBossConfig
    local entity = EntityServer.Create({cfgName = setting.entity, pos = setting.pos, map = setting.map})

    if entity then
        boss = entity
        local config = boss:cfg()
        boss:setValue("maxExp", config.maxHp)
        boss:setValue("curHp", config.maxHp)
    end
    return self
end

function ProcessWorldBoss:doJudge()

end

function ProcessWorldBoss:needKeepWaiting()
    return false
end

function ProcessWorldBoss:processOnTick()

end

return ProcessWorldBoss