---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/4/7 15:56
---

local ProcessBase = T(Game, "ProcessBase")
local ProcessTeam = T(Game, "ProcessTeam")
ProcessTeam.__index = ProcessBase