---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bell.
--- DateTime: 2020/3/21 22:45
---
local isDebug = false --是否是调试模式
local logLevel = 1 --日志等级
local prefixMap = {
    [1] = "Debug",
    [2] = "Info",
    [3] = "Warning",
    [4] = "Error",
    [5] = "Fatal",
}

local ConsoleTextColor = {
    ["FG_BLUE"] = 1,
    ["FG_GREEN"] = 2,
    ["FG_RED"] = 4,
    ["FG_INTENSITY"] = 8,
    ["BG_BLUE"] = 16,
    ["BG_GREEN"] = 32,
    ["BG_RED"] = 64,
    ["BG_INTENSITY"] = 128,
}

---@param level number
local function getPrefix(level)
    return prefixMap[level] or tostring(level)
end

---@param message string
---@param level number
function Lib.log(message, level)
    level = level or 1

    if not isDebug and level == 1 then
        return
    end

    if level < logLevel then
        return
    end

    --if PlatformUtil.isPlatformWindows() then
    --    if level == 1 then
    --        PlatformUtil.setConsoleTextColor(ConsoleTextColor.FG_GREEN)
    --    elseif level == 2 then
    --        PlatformUtil.setConsoleTextColor(ConsoleTextColor.FG_BLUE | ConsoleTextColor.FG_GREEN | ConsoleTextColor.FG_RED)
    --    elseif level == 3 then
    --        PlatformUtil.setConsoleTextColor(ConsoleTextColor.FG_GREEN | ConsoleTextColor.FG_RED)
    --    elseif level == 4 then
    --        PlatformUtil.setConsoleTextColor(ConsoleTextColor.FG_RED)
    --    end
    --end

    print(string.format("[%s] %s", getPrefix(level), message))
end

---@param value boolean
function Lib.setDebugLog(value)
    isDebug = value
end

---@param level number
function Lib.setLogLevel(level)
    logLevel = level
end

---@param level number
---@param prefix string
function Lib.setLogPrefixMap(level, prefix)
    prefixMap[level] = prefix
end