---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bell.
--- DateTime: 2020/4/16 20:27
---
---@class RegionShop

function RegionShop:onEntityEnter(entity, cfg)
    print("RegionShop:onEntityEnter")
end

function RegionShop:onEntityLeave(entity, cfg)
    print("RegionShop:onEntityLeave")
end

return RegionShop