---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bell.
--- DateTime: 2020/4/16 20:30
---
---@class RegionSell

function RegionSell:onEntityEnter(entity, cfg)
    print("RegionSell:onEntityEnter")

    entity:sellExp()
end

function RegionSell:onEntityLeave(entity, cfg)
    print("RegionSell:onEntityLeave")
end

return RegionSell