---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2020/4/23 20:35
---

---@class RegionIsland

function RegionIsland:onEntityEnter(entity, cfg)
    --print("RegionIsland:onEntityEnter")
end

function RegionIsland:onEntityLeave(entity, cfg)
    --print("RegionIsland:onEntityLeave")
end

return RegionIsland