---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2020/3/23 10:35
---
function Player:initPlayer()
    Lib.log("Player:initPlayer")

    self:initData()
    Blockman.Instance():setLockVisionState(World.cfg.lockVision and World.cfg.lockVision.open or false)
end

function Player:recoverJumpProp()
    self:setEntityProp("jumpSpeed", tostring(0.5))
    self:setEntityProp("gravity", tostring(0.08))
    self:setEntityProp("moveSpeed", tostring(0.2))
end