---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KH5C.
--- DateTime: 2020/4/1 11:52
---

Player.equipPetList = {};

function Player:callPet(index)

end

function Player:recallPet(index)

end
