---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KH5C.
--- DateTime: 2020/4/1 11:52
---

function Player:callPet(index, ridePoint)
    local packet = {
        pid = "callPet",
        index = index,
        ridePoint = ridePoint
    }
    self:sendPacket(packet)
end

function Player:getPet(index)
    return self.world:getEntity(index)
end

function Player:recallPet(index)
    local packet = {
        pid = "recallPet",
        index = index
    }
    self:sendPacket(packet)
end
