# user postion when enter game
initPos:
    -
        x: 4.0
        y: 60.0
        z: -17.0
    -
        x: -1.0
        y: 60.0
        z: -18.0
    -
        x: -6.0
        y: 60.0
        z: -17.0
    -
        x: -12.0
        y: 60.0
        z: -15.0
    -
        x: -16.0
        y: 60.0
        z: -12.0

# show player position on client.
enableOutputPos: false

# is enable break block
enableBreak: false

# is enable break block
clearChestWhenMove: false

# is enable ouput inventroy pos
enableFindInventory: false

# player's items when enter game
initItems: {}

waitingPlayerTime: 10

# player can move during this time
disableMoveTime: 10

# parpare time by second
prepareTime: 1

# game time by second
gameTime: 4200

# game over waiting time by second
gameOverTime: 10000

# final fight start time by second
ffStartTime: 10

# final fight time by second
ffTime: 120

# final fight position
ffPos:
    -
        x: 4.0
        y: 60.0
        z: -17.0
    -
        x: -1.0
        y: 60.0
        z: -18.0
    -
        x: -6.0
        y: 60.0
        z: -17.0
    -
        x: -12.0
        y: 60.0
        z: -15.0
    -
        x: -16.0
        y: 60.0
        z: -12.0

# when to refresh inventory after start game in second
inventoryRefreshTime: 240

vipRandomItem: {276: 1}

# supper player item
sppItems: {314: 1, 315: 1, 316: 1, 317: 1, 279: 1}

# classes items
clzItems:
  0: {314: 1, 315: 1, 316: 1, 317: 1, 279: 1}
  1: {279: 1, 314: 1, 315: 1, 316: 1, 317: 1}
  2: {272: 1, 302: 1, 303: 1, 304: 1, 305: 1}
  3: {311: 1}
  4: {261: 1, 262: 15}
  5: {268: 1, 298: 1, 299: 1, 300: 1, 301: 1}

# Position of inventory that will generate vip item possibly
vipItemInventories:
    -
        x: 6.0
        y: 60.0
        z: -17.0
    -
        x: 1.0
        y: 60.0
        z: -18.0
    -
        x: -4.0
        y: 60.0
        z: -17.0
    -
        x: -8.0
        y: 60.0
        z: -15.0
    -
        x: -14.0
        y: 60.0
        z: -12.0
# items in the inventory, and position of inventory
inventory:
    -
      fixedItems: {}
      # all range's first number must less than second
      foodNumRange: [1, 4]
      food:
          -
            id: 392
            randomRange: [4, 8]
            probability: 12
          -
            id: 319
            randomRange: [4, 8]
            probability: 8
          -
            id: 365
            randomRange: [4, 8]
            probability: 8
          -
            id: 260
            randomRange: [4, 8]
            probability: 8
          -
            id: 363
            randomRange: [4, 8]
            probability: 8
      equipNumRange: [2, 4]
      equip:
          -
            id: 298
            randomRange: [1, 2]
            probability: 9
          -
            id: 299
            randomRange: [1, 2]
            probability: 9
          -
            id: 300
            randomRange: [1, 2]
            probability: 9
          -
            id: 301
            randomRange: [1, 2]
            probability: 9
          -
            id: 314
            randomRange: [1, 2]
            probability: 7
      weaponNumRange: [0, 2]
      weapon:
          -
            id: 268
            randomRange: [1, 2]
            probability: 18
          -
            id: 271
            randomRange: [1, 2]
            probability: 18
          -
            id: 283
            randomRange: [1, 2]
            probability: 14
          -
            id: 286
            randomRange: [1, 2]
            probability: 14
          -
            id: 272
            randomRange: [1, 2]
            probability: 10
      materialsNumRange: [1, 3]
      materials:
          -
            id: 264
            randomRange: [1, 2]
            probability: 5
          -
            id: 265
            randomRange: [1, 2]
            probability: 15
          -
            id: 280
            randomRange: [5, 10]
            probability: 30
          -
            id: 259
            randomRange: [0, 1]
            probability: 15
          -
            id: 266
            randomRange: [1, 2]
            probability: 20
      pos:
          -
              x: 4.0
              y: 60.0
              z: -15.0
          -
              x: -1.0
              y: 60.0
              z: -16.0
          -
              x: -6.0
              y: 60.0
              z: -15.0
          -
              x: -12.0
              y: 60.0
              z: -13.0
          -
              x: -16.0
              y: 60.0
              z: -10.0