---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2020/4/1 20:36
---
---

local teamShopConfig = T(Config, "teamShopConfig")

local ItemStatus = {
    Buy = 1, --购买
    Used = 2, --已购买   装备
    Using = 3, --使用中   卸载
}

local teamShop = {}
function teamShop:onButtonClick(player, itemId, status)
    local config = teamShopConfig:getItemByItemId(itemId)
    if not config then
        print("!!!!!config--nil")
        return
    end
    if status == ItemStatus.Buy then
        self:onTeamShopItemBuy(player, itemId, status)
    elseif status == ItemStatus.Used then
        self:onTeamShopItemEquipUsed(player, itemId, status)
    elseif status == ItemStatus.Using then
        self:onTeamShopItemUnload(player, itemId, status)
    end
end

---卸载
function teamShop:onTeamShopItemUnload(player, id, status)
    self:updateTeamShopItem(player, id, status)
end

----使用
function teamShop:onTeamShopItemEquipUsed(player, id, status)
    self:updateTeamShopItem(player, id, status)
end

---购买
function teamShop:onTeamShopItemBuy(player, id, status)
    if not player then
        return
    end
    local item = teamShopConfig:getItemByItemId(id)
    if not item then
        return
    end
    --todo 扣钱操作
    player:consumeDiamonds("gDiamonds", item.price, function(ret)
        if ret then
            self:onBuyItemSuccess(player, id, status)
            return true
        end
    end)
end

function teamShop:onBuyItemSuccess(player, id, status)
    --TODO 装备外观
    self:updateTeamShopItem(player, id, status)
end

function teamShop:updateTeamShopItem(player, id, status)
    if status == ItemStatus.Buy then
        local info = Lib.copy(player:getOwnTeamSkin())
        for i, value in pairs(teamShopConfig:getItems()) do
            if value.id == id then
                table.insert(info, { id = id })
            end
        end
        player:setOwnTeamSkin(info)
    elseif status == ItemStatus.Used then
        local ownTeamSkin = Lib.copy(player:getOwnTeamSkin())
        for i, value in pairs(ownTeamSkin) do
            if value.id == id then
                player:setTeamSkinId(value.id)
            end
        end
    elseif status == ItemStatus.Using then
        local equipInfo = 0
        player:setTeamSkinId(equipInfo)
    end

end

return teamShop