---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KH5C.
--- DateTime: 2020/4/14 20:53
---

local widget_base = require "ui.widget.widget_base"
local M = Lib.derive(widget_base)

function M:init()
    widget_base.init(self, "NinjaPetPackagePetItem.json")
    self:initWnd()
end

function M:initWnd()
    self.image = self:child("PetPackageItem-PetImage")
    self.image:SetVisible(true)
    self.selectBroad = self:child("PetPackageItem-Select")
    self.selectBroad:SetVisible(false)
    self.usingBg = self:child("PetPackageItem-UsingBg")
    self.usingBg:SetVisible(false)
    self:child("PetPackageItem-UsingText"):SetText(Lang:toText("PetUsing"))
end

function M:using()
    self.usingBg:SetVisible(true)
end

function M:unUsing()
    self.usingBg:SetVisible(false)
end

function M:sel()
    self.selectBroad:SetVisible(true)
end

function M:unsel()
    self.selectBroad:SetVisible(false)
end

function M:initShow(id)
    self.image:SetImage("set:ninja_pet.json image:" .. tostring(id))
end

return M