---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KH5C.
--- DateTime: 2020/4/14 20:53
---

local widget_base = require "ui.widget.widget_base"
local M = Lib.derive(widget_base)


function M:init()
    widget_base.init(self, "NinjaPetPackagePlusPetItem.json")
    self:initWnd()
end

function M:initWnd()
    self.image = self:child("PlusPetItem-PlusPetImage")
    self.image:SetVisible(true)
    self.quality = self:child("PlusPetItem-PlusPetQuality")
    self.quality:SetVisible(true)
    self.selectBroad = self:child("PlusPetItem-PlusPetSelect")
    self.selectBroad:SetVisible(false)
    self.level = self:child("PlusPetItem-PlusPetLevelBg")
    self.levelText = self:child("PlusPetItem-PlusPetLevelText")
    self.using = self:child("PlusPetItem-PlusPetUsingBg")
    self.using:SetVisible(false)
    self:child("PlusPetItem-PlusPetUsingText"):SetText(Lang:toText("PlusPetUsing"))
    self.lock = self:child("PlusPetItem-Lock")
    self.lock:SetVisible(false)
end

function M:onClick()
    self.selectBroad:SetVisible(true)
end

function M:using()
    self.using:SetVisible(true)
end

function M:unUsing()
    self.using:SetVisible(false)
end

function M:sel()
    self.selectBroad:SetVisible(true)
end

function M:unsel()
    self.selectBroad:SetVisible(false)
end

function M:unEquip()
    self.using:SetVisible(false)
end

function M:initShow(id, quality, had, level)
    self.image:SetImage("set:ninja_pluspet.json image:" .. tostring(id))
    self.quality:SetImage("set:ninja_pluspet.json image:quality-" .. tostring(quality))
    if not had then
        self.lock:SetVisible(true)
        self.level:SetVisible(false)
    else
        self.levelText:SetText("Lv." .. tostring(level))
    end
end

return M;