---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2020/3/30 17:28
---

local widget_base = require "ui.widget.widget_base"
local M = Lib.derive(widget_base)
function M:init()
    widget_base.init(self, "CampStoreSkillPanel.json")
    self.ivSkillIcon = self:child("CampStoreSkillPanel-Skill-Icon")
    self.tvSkillName = self:child("CampStoreSkillPanel-Skill-Name")
    self.tvAttackText = self:child("CampStoreSkillPanel-Attack-Text")
    self.tvBloodText = self:child("CampStoreSkillPanel-Blood-Text")
    self.tvRightLv = self:child("CampStoreSkillPanel-Right-Lv")
    self.tvLeftLv = self:child("CampStoreSkillPanel-Left-Lv")

    self.tvValueText = self:child("CampStoreSkillPanel-Value-Text")
    self.tvValueProgress = self:child("CampStoreSkillPanel-Lv-Value")
end

function M:initSkillInfo(skillIcon, SkillName, Attack, Blood, RightLv, LeftLv, CurProgress, MaxProgress)

    self.ivSkillIcon:SetImage(skillIcon)
    self.tvSkillName:SetText(Lang:toText(SkillName))
    self.tvAttackText:SetText(Attack)
    self.tvBloodText:SetText(Blood)
    self.tvRightLv:SetText(RightLv)
    self.tvLeftLv:SetText(LeftLv)

    self.tvValueText:SetText(CurProgress .. "/" .. MaxProgress)
    self.tvValueProgress:SetProgress(CurProgress / MaxProgress)
end

function M:onInvoke(key, ...)
    local fn = M[key]
    assert(type(fn) == "function", key)
    return fn(self, ...)
end

return M