---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2020/3/30 19:50
---
local widget_base = require "ui.widget.widget_base"
local M = Lib.derive(widget_base)

---物品的状态
local ItemStatus = {
    Buy = 1, --购买
    Used = 2, --已购买   装备
    Using = 3, --使用中   卸载
}

---选中状态
local ItemSelectStatus = {
    NotSelect = 1,
    Select = 2,
}
function M:init()
    widget_base.init(self, "CampShopItem.json")

    self.ivItemContent = self:child("CampShopItem")
    self.ivItemIcon = self:child("CampShopItem-Item-Icon")
    self.ivPriceIcon = self:child("CampShopItem-Item-MoneyIcon")
    self.tvItemPrice = self:child("CampShopItem-Item-MoneyNum")
    self.ivItemSelected = self:child("CampShopItem-Item-Selected")
    self.ivItemSelected:SetVisible(false)
    self.btnItemBuy = self:child("CampShopItem-Item-Buy")
    self.btnItemBuy:SetVisible(false)

    self:subscribe(self.btnItemBuy, UIEvent.EventButtonClick, function()
        self:onClickItemBuy()
    end)
end

function M:onClickItemBuy()
    ---todo 发包给服务器
    --print("--------clickBuyButton-----" .. self.itemId .. "status" .. self.status)
    Me:sendPacket({
        pid = "teamShopBuyItem",
        itemId = self.itemId,
        status = self.status
    })
end

function M:onClickItem(id)
    if self.itemId == id then
        self.ivItemSelected:SetVisible(true)
    else
        self.ivItemSelected:SetVisible(false)
    end
end

function M:setItemData(id, icon, price, status)
    self.btnItemBuy:SetVisible(true)
    self.itemId = id
    self.status = status
    self.ivItemIcon:SetImage(icon)
    self:changeItemStatus(status, price)
end

function M:changeItemStatus(status, price)
    if status == ItemStatus.Buy then
        self.ivPriceIcon:SetVisible(true)
        self.ivPriceIcon:SetImage("set:LiftingSimulatorShop1.json image:DiamondGolds")
        self.tvItemPrice:SetText(price)
    elseif status == ItemStatus.Used then
        self.ivPriceIcon:SetVisible(false)
        self.tvItemPrice:SetVisible(false)
        local strButtonTitle = "GUIPayShop_Used" --使用
        self.btnItemBuy:SetText(Lang:toText(strButtonTitle))
    elseif status == ItemStatus.Using then
        self.ivPriceIcon:SetVisible(false)
        self.tvItemPrice:SetVisible(false)
        local strButtonTitle = "GUIPayShop_Unload" --已装备
        self.btnItemBuy:SetText(Lang:toText(strButtonTitle))
    end
end

function M:initItem(index)
    self.index = index
end

function M:onInvoke(key, ...)
    local fn = M[key]
    assert(type(fn) == "function", key)
    return fn(self, ...)
end

return M