---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2020/4/21 11:37
---

function M:init()
    WinBase.init(self, "NinjaRankTitle.json")
    print("!!!WinBase----NinjaRankTitle..........")
    self.RankTitle = self:child("NinjaRankTitle-title")
end

function M:refreshTextLang()
    if self.showRankType == 1 then
        self.RankTitle:SetText(Lang:toText("kill.rank.title"))
    elseif self.showRankType == 2 then
        self.RankTitle:SetText(Lang:toText("muscle.rank.title"))
    end
end

---rankType 对应ui配置表的args字段,打开不同排行榜的参数:1击杀榜，2积分榜，3.肌肉值榜.....
function M:onOpen(rankType)
    WinBase.onOpen(self)

    if rankType == self.showRankType then
        return
    end
    self.showRankType = rankType
    self:refreshTextLang()
end

function M:onClose()
end

return M