---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2020/4/21 11:38
---

function M:init()
    WinBase.init(self, "NinjaRankDown.json")
    print("!!!WinBase----NinjaRankDown..........")
    self.RankCountdown = self:child("NinjaRankDown-count-down")
    self.refreshTime = 20      --刷新时间
end

function M:refreshCountdown(key, time)
    local closeTimer = self.closeTimer
    if closeTimer then
        closeTimer()
        self.closeTimer = nil
    end
    local hours, min, second = Lib.timeFormatting(time)
    local message = string.format("%02d:%02d", min, second)
    self.RankCountdown:SetText(Lang:toText(key), message)
    local function tick()
        time = time - 1
        if time > 0 then
            local hours, min, second = Lib.timeFormatting(time)
            local message1 = string.format("%02d:%02d", min, second)
            local message2 = string.format(Lang:toText(key),
                    message1)
            self.RankCountdown:SetText(message2)
        end
        if time <= 0 then
            Rank.RequestRankData(1)
            self:refreshTextLang()
            return false
        end
        return time > 0
    end
    self.closeTimer = World.Timer(20, tick)
end

function M:refreshTextLang()

    if self.showRankType == 1 then
        self.refreshTime = 90
        self:refreshCountdown("rank.refresh.time", self.refreshTime)
    elseif self.showRankType == 2 then
        self.refreshTime = 40000
        self:refreshCountdown("rank.refresh.time", self.refreshTime)
    end

end

---rankType 对应ui配置表的args字段,打开不同排行榜的参数:1击杀榜，2积分榜，3.肌肉值榜.....
function M:onOpen(rankType)
    if rankType == self.showRankType then
        return
    end
    self.showRankType = rankType
    self:refreshTextLang()
end

function M:onClose()
end

return M