---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KH5C.
--- DateTime: 2020/4/21 10:00
---

function M:init()
    WinBase.init(self, "NinjaPlusPetEvolution.json",false)
    self:initWnd()
end



return M