---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JY-032.
--- DateTime: 2020/4/23 21:19
---

local RegionBase = require("world.region.region_base")
local RegionIsland = L("RegionIsland", Lib.derive(RegionBase))

local IslandConfig = T(Config, "IslandConfig")

local islandType = {
    unlock = 1, --已解锁
    lock = 2        --未解锁
}
function RegionIsland:onEntityEnter(entity, cfg)
    print("RegionIsland:onEntityEnter " .. cfg.islandId)

    local curIsland = cfg.islandId
    ----判断有没有解锁的，若没有解锁的岛屿id,则显示弹窗解锁提示，并且解锁下一个岛屿，存数据
    local island = IslandConfig:getIslandConfig(cfg.islandId)
    if not island then
        return
    end
    if island.islandType == islandType.unlock then
        self:onDialogTips(entity, island.subtitle)
        local islands = entity:getUnLockedIsland()
        local nextIsland = IslandConfig:getIslandConfig(island.nextIsland)
        if not self:isHaveIsland(entity, island.islandId) then
            table.insert(islands, { id = island.islandId })
            if nextIsland then
                table.insert(islands, { id = nextIsland.islandId })
            end
            entity:setUnLockedIsland(islands)
        end
        self:updateIslandLV(entity, nextIsland.islandLv)
    elseif island.islandType == islandType.lock then
        self:onDialogTips(entity, island.subtitle)
        local islands = entity:getUnLockedIsland()
        if self:isHaveIsland(entity, curIsland) then
            if not self:isHaveIsland(entity, island.nextIsland) then
                table.insert(islands, { id = island.nextIsland })
                entity:setUnLockedIsland(islands)
            end
        end
    end
end

function RegionIsland:onEntityLeave(entity, cfg)
    --print("RegionIsland:onEntityLeave " .. cfg.type)
end

---判断岛屿是否已经解锁过了
function RegionIsland:isHaveIsland(entity, island)
    local islands = entity:getUnLockedIsland()
    if not islands then
        return false
    end
    for i, va in pairs(islands) do
        if va.id == island then
            return true
        end
    end
    return false
end

---玩家的更新岛屿等级
function RegionIsland:updateIslandLV(entity, LV)
    entity:setIslandLv(LV)
end

function RegionIsland:onDialogTips(entity, tips)
    print("RegionIsland:onDialogTips ")

    UI:openWnd("ninjaCommonDialog"):initView(
            {
                content = Lang:toText(tips),
                contentCenter = true,
                txtTitle = Lang:toText("gui_tip"),
                hideClose = false,
                leftTxt = Lang:toText("gui_cancel"),
                rightTxt = Lang:toText("gui_sure"),
                leftCb = function()
                end,
                rightCb = function()
                end
            }
    )
end

RETURN(RegionIsland)