---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bell.
--- DateTime: 2020/4/16 19:49
---
local RegionBase = require("world.region.region_base")
local RegionShop = L("RegionShop", Lib.derive(RegionBase))
local bm = Blockman.instance

function RegionShop:isVaild(viewSetting, entity)
    if not entity.isPlayer then
        return false
    end
    return true
end

function RegionShop:onEntityEnter(entity, cfg)
    print("RegionShop:onEntityEnter")
end

function RegionShop:onEntityLeave(entity, cfg)
    print("RegionShop:onEntityLeave")
end

RETURN(RegionShop)