initPos: [-602, 11, -225]

#初始hp
hp: 50

#初始移动速度
moveSpeed: 200

#初始跳跃
jump: 0

#未受到伤害x秒后
withoutHurtSecond: 5

#回血CD
hpRecoverCD: 3

#回血量
hpRecover: 5

#离开战斗回血CD
awayFromBattleCD: 5

#转换率加成
convertRate: 1

#玩家初始可携带小鸟上限
initMaxCarryBirdNum: 2

#玩家初始背包小鸟容量上限
initMaxCapacityBirdNum: 10

#小鸟飞行高度
flyHigh: 2

#箭头坐标
arrowPointToNpcPos: [-610.5, 12, -224.5]

#引导NPC ID
arrowPointToNpc: 20009

#未购买vip时进入区域弹出购买界面
vipArea: [[-594, 10, -205], [-591, 13, -242]]

#触发商店箭头的金钱数量
shopTaskId: 1020801

#显示商店箭头
arrowPointToShopPos: [-605, 12, -260]

#显示商店的区域坐标
arrowShopArea: [[-612, 10, -258], [-598, 13, -270]]

#抽蛋引导任务ID
drawLuckyTaskId: 1022301

#抽蛋箭头坐标
drawLuckyPoint: [-623.5, 12, -214.5]

#生成大树的间隔时间(秒)
treeGenerateCD: 1800

#大树没人采集时的持续时间(秒)
treeRemainTime: 300

#大树从高等级向低等级重生的时间间隔(秒)
treeRespawnCD: 60

#增加可携带小鸟数引导任务ID
addCarryTo3TaskId: 1030501
addCarryTo4TaskId: 1040501

#喂食引导任务ID
feedTaskId: 2040701

#果币广告刷新时间间隔(单位：秒)
moneyAdRefreshTime: 900

#抽蛋票广告刷新时间间隔(单位：秒)
eggTicketAdRefreshTime: 900

#宝箱冷却广告刷新时间间隔(单位：秒)
chestCDAdRefreshTime: 900

#vip果币宝箱广告刷新时间点
vipChestADRefreshTime: ["00:00", "12:00"]

#喂养广告刷新时间间隔(单位：秒)
feedAdRefreshTime: 300

#果币广告收益(单位：果币)
moneyAdReward: 1500

#抽蛋票广告收益(单位：抽蛋票)
eggTicketAdReward: 3

#喂养广告收益(单位： 目前等级需要经验的百分比)
feedAdReward: 5