---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KH5C.
--- DateTime: 2020/4/1 10:10
---


local handles = T(Player, "PackageHandlers")

function handles:createPetEntity(packet)

end