---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KH5C.
--- DateTime: 2020/4/7 11:29
---

local function getActorNameFromPetID(petID)

end

-- Overwrite
-- Usage:该方法只用于在第一次获取宠物时调用
function Player:createPet(cfgName, show, map, pos)
    if show then
        map = map or self.map
        pos = pos or self:getFrontPos(2)
    else
        map = nil
        pos = nil
    end
    local petCfg = Entity.GetCfg(cfgName)
    local name = petCfg.name or self.name
    local entity = EntityServer.Create({cfgName = cfgName, map = map, pos = pos, name = name})
    return self:addPet(entity)
end

function Player.callPet(player, petID)
    local petActorName = getActorNameFromPetID(petID)
    if petActorName then
        --EntityServer:Create(petActorName, )

    else

    end
end

function Player.recallPet(player, petID)

end

