initPos: [292, 71, 282]
#领地释放时间
manorReleaseTime: 300
#领地默认的名字
defaultName: "BlockFort"
#玩家领地释放后用于修复地皮用的模板文件
groundName: "stone_50x50.schematic"
#主城传送点: x, y, z, yaw
teleportPos: [292, 71, 282, 0]
#预设水晶坐标
initCrystalPos: [24, 0, 24]
#预设水晶id
initCrystalId: 2002

#中断引导之后，传进领地的相对坐标
GuideSuspendTeleportRPos: [14, 1, 21]

inGuideLastId: 111