---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bell.
--- DateTime: 2020/4/16 16:51
---
---@class RegionManager
Lib.declare("RegionManager", {})

function RegionManager:init()
    --TODO
end

return RegionManager