---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bell.
--- DateTime: 2020/4/16 16:51
---
---@class RegionManager

function RegionManager:init()
    Lib.subscribeEvent("EVENT_REGION_ENTER", self.onRegionEnter)
    Lib.subscribeEvent("EVENT_REGION_LEAVE", self.onRegionLeave)
end

function RegionManager.onRegionEnter(param)
    print("RegionManager.onRegionEnter " .. param.inRegionKey)

    local cfg = param.regionCfg
    if not cfg.type then
        return
    end

    if cfg.type == "sell" then
        param.player:sellExp()
    end
end

function RegionManager.onRegionLeave(param)
    print("RegionManager.onRegionLeave " .. param.inRegionKey)
end

return RegionManager