---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bell.
--- DateTime: 2020/3/21 22:39
---
require "script_client.player.player"
require "script_client.player.player_event"
require "script_client.player.player_control"

local main = {}

function main:init()
    self:initLog()

    Lib.log("main:init")

    --TODO
end

function main:initLog()
    local isPcPlatform = (CGame.instance:getPlatformId() == 1)
    Lib.setDebugLog(isPcPlatform)
end

main:init()